### ISSUE TITLE
Bug in Temporal Module

### ISSUE THREAD

**Issue by hedlmote** [hyperfraise/Pytorch-StNet#2]
Hi, I found a mismatch between the original paper and your implementation.
x=x.view(B,C,T,H,W) in the TemporalBlock is not correct, there should be a transpose op instead of a reshape op.  "Reshape" block illustrated in the paper means to transpose a (BT, C, H, W) tensor into a (B, C, T, H, W) one for purpose of temporal modeling with Conv3d

**Comment by dmenig** [comment]
You're right. Fixing with 4a7e53c91e93d50b557d559ccb3b2d0d5bc99f9b

**Comment by dmenig** [comment]
Thank you for the review
