### ISSUE TITLE
How to install algorithmes?

### ISSUE THREAD

**Issue by dongyangcai** [hyperfraise/Pytorch-StNet#5]
Hi, I have read your code ,but I can't install the package algorithmes, sence the code have
"from algorithmes.deep.models.senet import SEResNeXtBottleneck"
can you tell me how to install algorithmes?

**Comment by dmenig** [comment]
Hi. I'm sorry that's a typo from me. It's a personal library. I'll fix this.

**Comment by dmenig** [comment]
Anyways, It linked to `senet.py` which is the file right next to it.
